export default {
  enUS: {
    title: "Typing Speed Test",
    subTitle: "How fast can you type?",
    langText: "Language",
    timeText: "Time",
    textAreaPlaceholderText: "Type after starting the test",
    startButtonText: "Start",
    numOfWordsText: "Words",
    numOfErrorsText: "Errors",
    numOfValidWordsText: "Valid words",
    resultText: "Result",
    levels: {
      1: "super slow 🐌",
      2: "slow 🐢",
      3: "under average 🌱",
      4: "average 👍",
      5: "over average 🙂",
      6: "fast 🤓",
      7: "very fast 🤩",
      8: "super fast 🚀",
    },
  },
  frFR: {
    title: "Test de vitesse de frappe",
    subTitle: "À quelle vitesse pouvez-vous taper?",
    langText: "Langue",
    timeText: "Temps",
    textAreaPlaceholderText: "Tapez après avoir commencé le test",
    startButtonText: "Démarrer",
    numOfWordsText: "Mots",
    numOfErrorsText: "Erreurs",
    numOfValidWordsText: "Mots valides",
    resultText: "Résultat",
    levels: {
      1: "très lentement 🐌",
      2: "lentement 🐢",
      3: "sous la moyenne 🌱",
      4: "moyenne 👍",
      5: "au dessus de la moyenne 🙂",
      6: "vite 🤓",
      7: "très vite 🤩",
      8: "super rapide 🚀",
    },
  },
  esES: {
    title: "Prueba de velocidad de escritura",
    subTitle: "¿Qué tan rápido puedes escribir?",
    langText: "Idioma",
    timeText: "Tiempo",
    textAreaPlaceholderText: "Escriba después de comenzar la prueba",
    startButtonText: "Inizio",
    numOfWordsText: "Palabras",
    numOfErrorsText: "Errores",
    numOfValidWordsText: "Palabras válidas",
    resultText: "Resultado",
    levels: {
      1: "super lento 🐌",
      2: "lento 🐢",
      3: "por debajo del promedio 🌱",
      4: "promedio 👍",
      5: "superior al promedio 🙂",
      6: "rapido 🤓",
      7: "muy rapido 🤩",
      8: "super rapido 🚀",
    },
  },
  itIT: {
    title: "Test di velocità di digitazione",
    subTitle: "Quanto veloce riesci a digitare?",
    langText: "linguaggio",
    timeText: "Tempo",
    textAreaPlaceholderText: "Digita dopo aver avviato il test",
    startButtonText: "Comienzo",
    numOfWordsText: "Parole",
    numOfErrorsText: "Errori",
    numOfValidWordsText: "Parole valide",
    resultText: "Risultato",
    levels: {
      1: "super lento 🐌",
      2: "lento 🐢",
      3: "sotto la media 🌱",
      4: "media 👍",
      5: "sopra la media 🙂",
      6: "veloce 🤓",
      7: "molto veloce 🤩",
      8: "super veloce 🚀",
    },
  },
  deDE: {
    title: "Tippgeschwindigkeitstest",
    subTitle: "Wie schnell kannst du tippen?",
    langText: "Sprache",
    timeText: "Zeit",
    textAreaPlaceholderText: "Type after starting the test",
    startButtonText: "Start",
    numOfWordsText: "Wörter",
    numOfErrorsText: "Fehler",
    numOfValidWordsText: "Gültige Wörter",
    resultText: "Ergebnis",
    levels: {
      1: "super langsam 🐌",
      2: "langsam 🐢",
      3: "unterdurchschnittlich 🌱",
      4: "durchschnittlich 👍",
      5: "überdurchschnittlich 🙂",
      6: "schnell 🤓",
      7: "sehr schnell 🤩",
      8: "super schnell 🚀",
    },
  },
}
